spring:
  bus:
    enabled: true
  trace:
    enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: my_vhost
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
