server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server
  client:
    #Don't register itself on Eureka
    register-with-eureka: false
    #Don't get register message from Eureka
    fetch-registry: false
    service-url:
       default-zone: http://localhost:8762/eureka
