server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server
    ip-address: 127.0.0.1
#    prefer-ip-address: true
  client:
    #Don't register itself on Eureka
    register-with-eureka: false
    #Don't get register message from Eureka
    fetch-registry: false
    service-url:
       defaultZone: http://localhost:8762/eureka

